### ISSUE TITLE
观星大佬我想了解xml配置文件获取

### ISSUE THREAD

**Issue by llsccm** [lucky-lele/sgshow#1]
我现在通过内存读取到了as3.0的sgs代码，但是没有相关经验，我想了解一下task.xml的获取方法

**Comment by llsccm** [comment]
之前社区找了你，不过你好像弃坑了，github联系不方便的话可以加一下qq p8203@qq.com

**Comment by lucky-lele** [comment]
既然你已经拿到了 AS 代码，那么找到 xml 是水到渠成的事情。想必对你而言不难，并且我猜想你已经成功了。如果确实如此，欢迎 fork 或者 commit 这个项目 :-)
[此前我的邮箱丢了，最近才把账号找回来]

**Comment by llsccm** [comment]
找不到as3.0的手册，不会调用解密模块，后面靠别人写出了代码qwq
这个项目的代码能看懂，动态图是一帧一帧截图下来再用ps合成吗？
还有就是代码中文字处理问题，我现在用正则处理，还有其他更好的方法吗？

**Comment by lucky-lele** [comment]
动态图是用 FFdec 把 swf 帧导出，原始 swf 帧率一般是 24 或 30，这里每 0.1 秒取一帧。然后用 ImageMagick 拼成 sprite sheet，最后线上版有损压缩、线下版无损压缩。因为基本都是命令行工具，完整流程用的 bash 脚本（包括自动生成项目中的 html、xml等文件）。但是比较复杂，而且不具备可移植性，所以没有公开。
没看懂你说的文字处理的问题到底是什么。xml 解析我用的是 xmllint，有时候会用 grep （偶尔用到正则表达式）。
这个项目我有空还是会更新，毕竟舍不得就这么放弃，但是可能不会那么频繁。
最后感谢关注 :-)
